spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: sharding-jdbc
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      names: master0,master0slave0,master0slave1
      master0:
        driverClassName: com.mysql.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/master0?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root
      master0slave0:
        driverClassName: com.mysql.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/master0slave0?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root
      master0slave1:
        driverClassName: com.mysql.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/master0slave1?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root
    masterslave:
      name: ms
      master-data-source-name: master0
      slave-data-source-names: master0slave0,master0slave1

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
server:
  port: 8081